# Generated by Django 4.0.2 on 2022-03-15 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0002_alter_category_options_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='spicy_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
